version: "3.9"

services:
  kourichat:
    build: .
    container_name: kourichat_daily
    volumes:
      - ./data:/app/data  # 配置、数据持久化
    ports:
      - "7860:7860"        # WebUI 端口
      - "8081:8081"        # 企业微信 Webhook 回调端口
    command: ["python", "run.py"]
    restart: unless-stopped
